/**
 * AI Security Agent — GitHub integration.
 *
 * Creates issues from findings and posts security summaries to PRs using the
 * existing Octokit client. Issue bodies are redacted before leaving the app.
 */

import { createOctokit } from "@/lib/github";
import { redactSecrets } from "./utils";
import type { Verdict } from "./types";

export function severityEmoji(s: string): string {
  switch (s) {
    case "critical": return "🔴";
    case "high": return "🟠";
    case "medium": return "🟡";
    default: return "🔵";
  }
}

export function verdictEmoji(v: string | null): string {
  switch (v) {
    case "confirmed": return "✅ Confirmed";
    case "likely": return "🟠 Likely";
    case "potential": return "🟡 Potential";
    case "false_positive": return "⚪ False Positive";
    default: return "❔ Unassessed";
  }
}

export interface IssueFinding {
  title: string;
  severity: string;
  verdict: string | null;
  cweId?: string | null;
  cveId?: string | null;
  file?: string | null;
  line?: number | null;
  rootCause?: string | null;
  impact?: string | null;
  recommendation?: string | null;
  aiAnalysis?: string | null;
}

export function formatIssueBody(f: IssueFinding): string {
  return [
    `## ${severityEmoji(f.severity)} ${f.title}`,
    "",
    "> Reported by the **DevWatch AI Security Agent** — Detect → Investigate → Validate → Remediate → Verify",
    "",
    `| Field | Value |`,
    `| --- | --- |`,
    `| Severity | ${severityEmoji(f.severity)} ${f.severity} |`,
    `| Verdict | ${verdictEmoji(f.verdict)} |`,
    f.cweId ? `| CWE | ${f.cweId} |` : "",
    f.cveId ? `| CVE | ${f.cveId} |` : "",
    f.file ? `| File | \`${f.file}${f.line ? `:${f.line}` : ""}\` |` : "",
    "",
    f.rootCause ? `### Root cause\n${f.rootCause}\n` : "",
    f.impact ? `### Potential impact\n${f.impact}\n` : "",
    f.recommendation ? `### Recommended remediation\n${f.recommendation}\n` : "",
    f.aiAnalysis ? `### AI investigation\n<details>\n<summary>Analysis</summary>\n\n${f.aiAnalysis}\n\n</details>\n` : "",
    "",
    "---",
    "_Generated by DevWatch AI Security Agent. Findings are proposals for human review — no patch is merged automatically._",
  ]
    .filter(Boolean)
    .join("\n");
}

export function formatPRComment(summary: {
  critical: number;
  high: number;
  medium: number;
  low: number;
  status: string;
  findings: Array<{ title: string; severity: string; file?: string | null }>;
}): string {
  const statusLine =
    summary.critical > 0 || summary.high > 0 ? "🔴 Changes Required" : summary.medium > 0 ? "🟠 Review Required" : "🟢 No High-Risk Issues";

  return [
    `## 🛡️ Security Agent`,
    `──────────────────`,
    `| Critical | High | Medium | Low |`,
    `| --- | --- | --- | --- |`,
    `| ${summary.critical} | ${summary.high} | ${summary.medium} | ${summary.low} |`,
    "",
    `**Security Status:** ${statusLine}`,
    "",
    ...(summary.findings.length
      ? [
          "<details>",
          "<summary>Findings</summary>",
          "",
          ...summary.findings.map((f) => `- ${severityEmoji(f.severity)} **${f.title}**${f.file ? ` — \`${f.file}\`` : ""}`),
          "",
          "</details>",
        ]
      : ["✅ No security findings detected in the changed files."]),
    "",
    `_Posted by DevWatch AI Security Agent_`,
  ].join("\n");
}

export async function createSecurityIssue(opts: {
  owner: string;
  repo: string;
  token?: string;
  finding: IssueFinding;
}): Promise<{ issueUrl: string; issueNumber: number }> {
  const octokit = createOctokit(opts.token);
  const body = redactSecrets(formatIssueBody(opts.finding));
  const res = await octokit.rest.issues.create({
    owner: opts.owner,
    repo: opts.repo,
    title: `[Security] ${severityEmoji(opts.finding.severity)} ${opts.finding.title}`,
    body,
    labels: ["security", `severity:${opts.finding.severity}`].filter(Boolean),
  });
  return { issueUrl: res.data.html_url, issueNumber: res.data.number };
}

export async function postSecurityPRComment(opts: {
  owner: string;
  repo: string;
  pullNumber: number;
  token?: string;
  summary: Parameters<typeof formatPRComment>[0];
}): Promise<{ commentUrl: string }> {
  const octokit = createOctokit(opts.token);
  const res = await octokit.rest.issues.createComment({
    owner: opts.owner,
    repo: opts.repo,
    issue_number: opts.pullNumber,
    body: redactSecrets(formatPRComment(opts.summary)),
  });
  return { commentUrl: res.data.html_url };
}

export type { Verdict };
