/**
 * Security Agent — GitHub integration.
 *
 * Uses the existing GitHub REST service (src/lib/server/github) to:
 *   - create a GitHub issue from a finding (formatted summary)
 *   - attach a security status block to a PR
 *
 * The agent never merges or pushes — issues and PR text only.
 */

import { z } from "zod";
import { ValidationError } from "@/lib/errors";
import { type GitHubConfig } from "../github";
import type { PrismaClient, SecurityFinding } from "@prisma/client";

export const githubIssueInputSchema = z.object({
  projectId: z.string().min(1),
  findingId: z.string().min(1),
  title: z.string().max(200).optional(),
});

export interface GitHubIssueResult {
  issueNumber: number;
  issueUrl: string;
}

/** Build the markdown issue body for a finding. */
export function formatFindingAsIssue(finding: {
  title: string;
  ruleId: string;
  severity: string;
  confidence: number;
  cwe?: string | null;
  cve?: string | null;
  filePath?: string | null;
  lineStart?: number | null;
  rootCause?: string | null;
  impact?: string | null;
  aiAnalysis?: string | null;
  verdict?: string | null;
  status: string;
  attackPath?: unknown;
  evidence?: unknown;
}): string {
  const attackPath = Array.isArray(finding.attackPath)
    ? (finding.attackPath as { label: string; detail: string; file?: string; line?: number }[])
    : [];

  const lines = [
    `## 🔒 Security Agent finding`,
    ``,
    `| Field | Value |`,
    `|---|---|`,
    `| Severity | ${finding.severity} |`,
    `| Confidence | ${finding.confidence}% |`,
    `| Rule | \`${finding.ruleId}\` |`,
    `| CWE | ${finding.cwe ?? "—"} |`,
    `| CVE | ${finding.cve ?? "—"} |`,
    `| Location | ${finding.filePath ?? "—"}${finding.lineStart ? `:${finding.lineStart}` : ""} |`,
    `| Status | ${finding.status} |`,
    `| Verdict | ${finding.verdict ?? "—"} |`,
    ``,
    `### Root cause`,
    finding.rootCause ?? "_Not determined._",
    ``,
    `### Impact`,
    finding.impact ?? "_Not assessed._",
    ``,
    `### Attack path`,
    attackPath.length
      ? attackPath.map((s, i) => `${i + 1}. **${s.label}** — ${s.detail}${s.file ? ` (\`${s.file}${s.line ? `:${s.line}` : ""}\`)` : ""}`).join("\n")
      : "_Not traced._",
    ``,
    `### AI analysis`,
    finding.aiAnalysis ?? "_Pending investigation._",
    ``,
    `---`,
    `_Generated by DevWatch AI Security Agent — review before acting._`,
  ];
  return lines.join("\n");
}

/** Format a security-status block for a PR comment. */
export function formatPrSecurityComment(findings: {
  severity: string;
  status: string;
  title: string;
}[]): string {
  const counts = { critical: 0, high: 0, medium: 0, low: 0 };
  for (const f of findings) {
    const s = f.severity.toLowerCase();
    if (s in counts) counts[s as keyof typeof counts]++;
  }
  const total = findings.length;
  const status =
    counts.critical > 0
      ? "🚨 Critical findings — fix before merge"
      : counts.high > 0
        ? "⚠️ Review required"
        : total > 0
          ? "🟡 Minor findings"
          : "✅ No open security findings";

  return [
    `## 🔒 Security Agent`,
    `──────────────────`,
    `Critical: ${counts.critical}`,
    `High: ${counts.high}`,
    `Medium: ${counts.medium}`,
    `Low: ${counts.low}`,
    ``,
    `Security Status:`,
    `${status}`,
    ``,
    total
      ? findings.slice(0, 10).map((f) => `- [${f.severity.toUpperCase()}] ${f.title} (${f.status})`).join("\n")
      : `_No open findings for this repository._`,
  ].join("\n");
}

/** Resolve the GitHub config (project token → env token) for a project. */
export async function resolveGithubConfig(
  db: PrismaClient,
  projectId: string
): Promise<{ config: GitHubConfig | null; repoFullName: string | null }> {
  const project = await db.project.findUnique({ where: { id: projectId }, select: { aiConfig: true } });
  const cfg = (project?.aiConfig ?? {}) as { githubToken?: string; githubRepo?: string };
  let token: string | null = null;
  if (cfg.githubToken) {
    const { decryptSecret } = await import("../crypto");
    token = decryptSecret(cfg.githubToken);
  }
  token = token ?? process.env.GITHUB_TOKEN ?? null;
  return {
    config: token ? { token } : null,
    repoFullName: cfg.githubRepo ?? null,
  };
}

/** Create a GitHub issue for a finding. */
export async function createIssueForFinding(opts: {
  finding: SecurityFinding;
  actorId: string;
}): Promise<GitHubIssueResult> {
  const db = (await import("../db")).requireDb();
  const { config, repoFullName } = await resolveGithubConfig(db, opts.finding.projectId);
  if (!config) throw new ValidationError("GitHub is not connected for this project. Connect it first.");
  if (!repoFullName) throw new ValidationError("No repository is linked to this project. Link one first.");

  const [owner, repo] = repoFullName.split("/");
  const body = formatFindingAsIssue(opts.finding);
  const title = `[Security] ${opts.finding.severity}: ${opts.finding.title}`.slice(0, 180);

  // The existing service exposes createOrUpdateFiles/createRepo but not
  // issue creation; use the fetch helper through a minimal call here.
  const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues`, {
    method: "POST",
    headers: {
      "Accept": "application/vnd.github.v3+json",
      "Authorization": `Bearer ${config.token}`,
      "Content-Type": "application/json",
      "User-Agent": "DevWatch-Security-Agent",
    },
    body: JSON.stringify({
      title,
      body,
      labels: ["security", `severity-${opts.finding.severity.toLowerCase()}`],
    }),
    signal: AbortSignal.timeout(15_000),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new ValidationError(`GitHub issue creation failed (${res.status}). ${text.slice(0, 200)}`);
  }
  const issue = (await res.json()) as { number: number; html_url: string };

  await db.securityAction.create({
    data: {
      projectId: opts.finding.projectId,
      findingId: opts.finding.id,
      actorId: opts.actorId,
      tool: "CREATE_GITHUB_ISSUE",
      action: `created issue #${issue.number}`,
      authScope: "USER",
      authorized: true,
      result: { issueNumber: issue.number, issueUrl: issue.html_url },
    },
  });

  return { issueNumber: issue.number, issueUrl: issue.html_url };
}
