import {
  Stethoscope,
  Clock,
  Activity,
  Gauge,
  Thermometer,
  Languages,
  Heart,
  HeartPulse,
  Wind,
  Snowflake,
  Utensils,
  Droplet,
  Droplets,
  Scale,
  Ruler,
  Calculator,
  Smile,
  MessageSquare,
  User,
  UserCheck,
  UserPlus,
  Mic,
  Sparkles,
  FileText,
  ClipboardCheck,
  Calendar,
  Pill,
  Info,
  Cigarette,
  Wine,
  Dumbbell,
  Salad,
  Bed,
  Brain,
} from 'lucide-react'

// String-keyed icon registry so plain data files can reference icons.
export const iconMap = {
  stethoscope: Stethoscope,
  clock: Clock,
  activity: Activity,
  gauge: Gauge,
  thermometer: Thermometer,
  languages: Languages,
  heart: Heart,
  heartPulse: HeartPulse,
  wind: Wind,
  snowflake: Snowflake,
  utensils: Utensils,
  droplet: Droplet,
  droplets: Droplets,
  scale: Scale,
  ruler: Ruler,
  calculator: Calculator,
  smile: Smile,
  message: MessageSquare,
  user: User,
  userCheck: UserCheck,
  userPlus: UserPlus,
  mic: Mic,
  sparkles: Sparkles,
  fileText: FileText,
  clipboardCheck: ClipboardCheck,
  calendar: Calendar,
  pill: Pill,
  info: Info,
  cigarette: Cigarette,
  wine: Wine,
  dumbbell: Dumbbell,
  salad: Salad,
  bed: Bed,
  brain: Brain,
}

export function Ico({ name, ...props }) {
  const Cmp = iconMap[name] || Info
  return <Cmp {...props} />
}
