import path from "node:path";
import os from "node:os";

/**
 * Sandbox directory where generated apps are materialized for real verification.
 * Uses the OS temp dir because serverless runtimes (Vercel) expose a writable
 * /tmp but the project directory is read-only at runtime. Locally this also
 * keeps generated projects out of the repo.
 */
export function workspaceDir(projectId: string): string {
  return path.join(os.tmpdir(), "webforge-workspaces", "apps", projectId);
}

/**
 * Starter files written when a project's app workspace is first created.
 * The generated app is a minimal, real, runnable TypeScript project — the AI
 * agent then adds application files on top. Dev dependencies (typescript,
 * vitest) resolve from the npm cache, so verification works offline.
 */
export function starterFiles(name: string): Record<string, string> {
  const safeName = (name || "webforge-app").toLowerCase().replace(/[^a-z0-9-]+/g, "-").slice(0, 40) || "webforge-app";
  return {
    "package.json": JSON.stringify(
      {
        name: safeName,
        version: "1.0.0",
        private: true,
        scripts: {
          dev: "tsx watch src/index.ts",
          build: "tsc",
          start: "node dist/index.js",
          test: "vitest run",
          typecheck: "tsc --noEmit",
        },
        dependencies: {},
        devDependencies: {
          typescript: "^5.8.3",
          tsx: "^4.19.0",
          vitest: "^3.2.4",
          "@types/node": "^22.15.0",
        },
      },
      null,
      2
    ) + "\n",
    "tsconfig.json": JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "commonjs",
          moduleResolution: "node",
          outDir: "dist",
          rootDir: "src",
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          forceConsistentCasingInFileNames: true,
          resolveJsonModule: true,
          jsx: "react-jsx",
        },
        include: ["src"],
      },
      null,
      2
    ) + "\n",
    ".env.example": `# ${name} — environment variables\n# Copy to .env and fill in real values. Secrets are never committed.\nAPP_NAME=${safeName}\nNODE_ENV=development\nPORT=3000\n`,
    "src/index.ts": `/**
 * ${name} — generated by WebForge AI.
 * Entry point that starts the server and handles graceful shutdown.
 */

import { startServer } from "./server";

async function main() {
  const port = parseInt(process.env.PORT || "3000", 10);
  const server = await startServer(port);
  
  process.on("SIGTERM", () => {
    console.log("SIGTERM received, shutting down...");
    server.close(() => process.exit(0));
  });
  
  process.on("SIGINT", () => {
    console.log("SIGINT received, shutting down...");
    server.close(() => process.exit(0));
  });
}

main().catch((err) => {
  console.error("Failed to start server:", err);
  process.exit(1);
});
`,
    "src/server.ts": `/**
 * Express server with health check and API routes.
 */

import express from "express";
import cors from "cors";
import { env } from "./lib/env";

export function startServer(port: number) {
  const app = express();
  
  // Middleware
  app.use(cors());
  app.use(express.json());
  
  // Health check
  app.get("/api/health", (_req, res) => {
    res.json({
      status: "ok",
      app: env("APP_NAME", "${safeName}"),
      uptime: process.uptime(),
      timestamp: new Date().toISOString(),
    });
  });
  
  // TODO: Add your API routes here
  
  return new Promise<ReturnType<typeof app.listen>>((resolve) => {
    const server = app.listen(port, () => {
      console.log(\`🚀 Server running on http://localhost:\${port}\`);
      resolve(server);
    });
  });
}
`,
    "src/lib/env.ts": `/** Minimal, safe environment loader — no secrets are ever logged. */
export function env(key: string, fallback?: string): string {
  const value = process.env[key];
  if (value !== undefined && value !== "") return value;
  if (fallback !== undefined) return fallback;
  throw new Error(\`Missing required environment variable \${key}\`);
}

export function hasEnv(key: string): boolean {
  const v = process.env[key];
  return v !== undefined && v !== "";
}
`,
    "src/__tests__/smoke.test.ts": `import { describe, expect, it } from "vitest";
import { startServer } from "../server";

describe("${safeName} server", () => {
  it("starts and responds to health check", async () => {
    const port = 3099 + Math.floor(Math.random() * 100);
    const server = await startServer(port);
    try {
      const res = await fetch(\`http://localhost:\${port}/api/health\`);
      expect(res.ok).toBe(true);
      const data = await res.json();
      expect(data.status).toBe("ok");
    } finally {
      server.close();
    }
  });
});
`,
  };
}

/** True when the workspace already has application files (beyond the starter set). */
export function hasRealFiles(files: Record<string, string>): boolean {
  const starters = new Set(Object.keys(starterFiles("x")));
  return Object.keys(files).some((p) => !starters.has(p));
}