import path from "node:path";

/** Sandbox directory where generated apps are materialized for real verification. */
export function workspaceDir(projectId: string): string {
  return path.join(process.cwd(), "workspaces", "apps", projectId);
}

/**
 * Starter files written when a project's app workspace is first created.
 * The generated app is a minimal, real, runnable TypeScript project — the AI
 * agent then adds application files on top. Dev dependencies (typescript,
 * vitest) resolve from the npm cache, so verification works offline.
 */
export function starterFiles(name: string): Record<string, string> {
  const safeName = (name || "webforge-app").toLowerCase().replace(/[^a-z0-9-]+/g, "-").slice(0, 40) || "webforge-app";
  return {
    "package.json": JSON.stringify(
      {
        name: safeName,
        version: "1.0.0",
        private: true,
        scripts: {
          build: "tsc",
          start: "node dist/index.js",
          test: "vitest run",
          typecheck: "tsc --noEmit",
        },
        devDependencies: {
          typescript: "^5.8.3",
          vitest: "^3.2.4",
          "@types/node": "^22.15.0",
        },
      },
      null,
      2
    ) + "\n",
    "tsconfig.json": JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "commonjs",
          moduleResolution: "node",
          outDir: "dist",
          rootDir: "src",
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          forceConsistentCasingInFileNames: true,
          resolveJsonModule: true,
        },
        include: ["src"],
      },
      null,
      2
    ) + "\n",
    ".env.example": `# WebForge generated app — environment variables\n# Copy to .env and fill in real values. Secrets are never committed.\nAPP_NAME=${safeName}\nNODE_ENV=development\n`,
    "src/index.ts": `/**
 * ${name} — generated by WebForge AI.
 * Structured source of truth lives in the WebForge workspace; this sandbox
 * copy is materialized only to run real verification (typecheck, tests, build).
 */

import { env } from "./lib/env";

export interface HealthReport {
  app: string;
  nodeEnv: string;
  checks: { name: string; ok: boolean }[];
}

/** Real self-check exercised by the automated pipeline's runtime step. */
export function healthCheck(): HealthReport {
  const checks = [
    { name: "env.loader", ok: typeof env === "function" },
    { name: "startup", ok: true },
  ];
  return { app: env("APP_NAME", "webforge-app"), nodeEnv: env("NODE_ENV", "development"), checks };
}

export function main(): void {
  const report = healthCheck();
  console.log(JSON.stringify(report, null, 2));
  if (report.checks.some((c) => !c.ok)) {
    process.exitCode = 1;
  }
}

if (require.main === module) {
  main();
}
`,
    "src/lib/env.ts": `/** Minimal, safe environment loader — no secrets are ever logged. */
export function env(key: string, fallback?: string): string {
  const value = process.env[key];
  if (value !== undefined && value !== "") return value;
  if (fallback !== undefined) return fallback;
  throw new Error(\`Missing required environment variable \${key}\`);
}

export function hasEnv(key: string): boolean {
  const v = process.env[key];
  return v !== undefined && v !== "";
}
`,
    "src/__tests__/smoke.test.ts": `import { describe, expect, it } from "vitest";
import { healthCheck } from "../index";

describe("webforge app", () => {
  it("runs a health check with every check passing", () => {
    const report = healthCheck();
    expect(report.app.length).toBeGreaterThan(0);
    expect(report.checks.every((c) => c.ok)).toBe(true);
  });
});
`,
  };
}

/** True when the workspace already has application files (beyond the starter set). */
export function hasRealFiles(files: Record<string, string>): boolean {
  const starters = new Set(Object.keys(starterFiles("x")));
  return Object.keys(files).some((p) => !starters.has(p));
}